export default {
    UNSET_ALL: 'unsetAll',
    UNSET_LIST: 'unsetList',
    SET_DATA: 'setData',
    CREATE: 'create',
    UPDATE: 'update',
    PATCH: 'patch',
    DELETE: 'delete',
    FIND_ALL: 'findAll',
    FIND_BY_ID: 'findById',
    SET_ROWS: 'setRows',
    SET_LIST: 'setList',
    SET_COUNT: 'setCount',
    SET_PAGE: 'setPage',
    SET_TOTALPAGE: 'setTotalPage',
    SET_SEARCHING: 'setSearching',
    SET_SEARCH_START: 'setSearchStart',
    SET_SEARCH_END: 'setSearchEnd',
    UPDATED: 'updated',
}